# generated by datamodel-codegen:
#   filename:  /var/folders/x1/p1jlgprs7_g3l7tkwv4_ksx40000gn/T/tmp3tr5ixr4/openapi.yaml
#   timestamp: 2025-03-17T11:55:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, RootModel


class Audience(Enum):
    general = 'general'
    technical = 'technical'
    business = 'business'
    academic = 'academic'


class InputSchema(BaseModel):
    email: str
    audience: Audience


class OutputSchema(BaseModel):
    correct: bool
    corrected_email: Optional[str] = None


class ConfigSchema(RootModel[Any]):
    root: Any
