# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.api.threads_api import ThreadsApi


class TestThreadsApi(unittest.TestCase):
    """ThreadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ThreadsApi()

    def tearDown(self) -> None:
        pass

    def test_create_thread(self) -> None:
        """Test case for create_thread

        Create an empty Thread
        """
        pass

    def test_delete_thread(self) -> None:
        """Test case for delete_thread

        Delete a thread. If the thread contains any pending run, deletion fails.
        """
        pass

    def test_get_run_threadstate(self) -> None:
        """Test case for get_run_threadstate

        Retrieve the thread state at the end of the run
        """
        pass

    def test_get_thread(self) -> None:
        """Test case for get_thread

        Get a previously created Thread
        """
        pass

    def test_get_thread_history(self) -> None:
        """Test case for get_thread_history

        Retrieve the list of runs and associated state at the end of each run.
        """
        pass

    def test_get_thread_state(self) -> None:
        """Test case for get_thread_state

        Retrieve the current state associated with the thread
        """
        pass

    def test_search_threads(self) -> None:
        """Test case for search_threads

        Search Threads
        """
        pass


if __name__ == '__main__':
    unittest.main()
