# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.docker_deployment import DockerDeployment

class TestDockerDeployment(unittest.TestCase):
    """DockerDeployment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DockerDeployment:
        """Test DockerDeployment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DockerDeployment`
        """
        model = DockerDeployment()
        if include_optional:
            return DockerDeployment(
                type = 'docker',
                image = '',
                protocol = acp_client_v0_1.models.acp_details.ACP Details(
                    type = 'ACP', 
                    url = '', 
                    agent_id = '', 
                    authentication = acp_client_v0_1.models.security_scheme.SecurityScheme(), )
            )
        else:
            return DockerDeployment(
                type = 'docker',
                image = '',
                protocol = acp_client_v0_1.models.acp_details.ACP Details(
                    type = 'ACP', 
                    url = '', 
                    agent_id = '', 
                    authentication = acp_client_v0_1.models.security_scheme.SecurityScheme(), ),
        )
        """

    def testDockerDeployment(self):
        """Test DockerDeployment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
