# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.agent_manifest_deployments_inner import AgentManifestDeploymentsInner

class TestAgentManifestDeploymentsInner(unittest.TestCase):
    """AgentManifestDeploymentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentManifestDeploymentsInner:
        """Test AgentManifestDeploymentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentManifestDeploymentsInner`
        """
        model = AgentManifestDeploymentsInner()
        if include_optional:
            return AgentManifestDeploymentsInner(
                type = 'source_code',
                name = '',
                url = '',
                framework_config = None,
                protocol = acp_client_v0_1.models.acp_details.ACP Details(
                    type = 'ACP', 
                    url = '', 
                    agent_id = '', 
                    authentication = acp_client_v0_1.models.security_scheme.SecurityScheme(), ),
                image = ''
            )
        else:
            return AgentManifestDeploymentsInner(
                type = 'source_code',
                url = '',
                framework_config = None,
                protocol = acp_client_v0_1.models.acp_details.ACP Details(
                    type = 'ACP', 
                    url = '', 
                    agent_id = '', 
                    authentication = acp_client_v0_1.models.security_scheme.SecurityScheme(), ),
                image = '',
        )
        """

    def testAgentManifestDeploymentsInner(self):
        """Test AgentManifestDeploymentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
