# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.agent_manifest_ref import AgentManifestRef

class TestAgentManifestRef(unittest.TestCase):
    """AgentManifestRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentManifestRef:
        """Test AgentManifestRef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentManifestRef`
        """
        model = AgentManifestRef()
        if include_optional:
            return AgentManifestRef(
                name = '',
                version = '',
                url = ''
            )
        else:
            return AgentManifestRef(
                name = '',
                version = '',
        )
        """

    def testAgentManifestRef(self):
        """Test AgentManifestRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
