# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.agent_specs_interrupts_inner import AgentSpecsInterruptsInner

class TestAgentSpecsInterruptsInner(unittest.TestCase):
    """AgentSpecsInterruptsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentSpecsInterruptsInner:
        """Test AgentSpecsInterruptsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentSpecsInterruptsInner`
        """
        model = AgentSpecsInterruptsInner()
        if include_optional:
            return AgentSpecsInterruptsInner(
                interrupt_type = '',
                interrupt_payload = acp_client_v0_1.models.interrupt_payload.interrupt_payload(),
                resume_payload = acp_client_v0_1.models.interrupt_payload.interrupt_payload()
            )
        else:
            return AgentSpecsInterruptsInner(
                interrupt_type = '',
                interrupt_payload = acp_client_v0_1.models.interrupt_payload.interrupt_payload(),
                resume_payload = acp_client_v0_1.models.interrupt_payload.interrupt_payload(),
        )
        """

    def testAgentSpecsInterruptsInner(self):
        """Test AgentSpecsInterruptsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
