# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.agent_connect_protocol import AgentConnectProtocol

class TestAgentConnectProtocol(unittest.TestCase):
    """AgentConnectProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentConnectProtocol:
        """Test AgentConnectProtocol
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentConnectProtocol`
        """
        model = AgentConnectProtocol()
        if include_optional:
            return AgentConnectProtocol(
                type = 'ACP',
                url = '',
                agent_id = '',
                authentication = acp_client_v0_1.models.security_scheme.SecurityScheme()
            )
        else:
            return AgentConnectProtocol(
                type = 'ACP',
                url = '',
        )
        """

    def testAgentConnectProtocol(self):
        """Test AgentConnectProtocol"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
