# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.lang_graph_config import LangGraphConfig

class TestLangGraphConfig(unittest.TestCase):
    """LangGraphConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LangGraphConfig:
        """Test LangGraphConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LangGraphConfig`
        """
        model = LangGraphConfig()
        if include_optional:
            return LangGraphConfig(
                framework_type = 'langgraph',
                graph = ''
            )
        else:
            return LangGraphConfig(
                framework_type = 'langgraph',
                graph = '',
        )
        """

    def testLangGraphConfig(self):
        """Test LangGraphConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
