# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.streaming_mode import StreamingMode

class TestStreamingMode(unittest.TestCase):
    """StreamingMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamingMode(self):
        """Test StreamingMode"""
        # inst = StreamingMode()

if __name__ == '__main__':
    unittest.main()
