# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.streaming_modes import StreamingModes

class TestStreamingModes(unittest.TestCase):
    """StreamingModes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreamingModes:
        """Test StreamingModes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreamingModes`
        """
        model = StreamingModes()
        if include_optional:
            return StreamingModes(
                result = True,
                custom = True
            )
        else:
            return StreamingModes(
        )
        """

    def testStreamingModes(self):
        """Test StreamingModes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
