# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.api.runs_api import RunsApi


class TestRunsApi(unittest.TestCase):
    """RunsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RunsApi()

    def tearDown(self) -> None:
        pass

    def test_create_run(self) -> None:
        """Test case for create_run

        Create Background Run
        """
        pass

    def test_delete_run(self) -> None:
        """Test case for delete_run

        Delete a run. If running, cancel and then delete.
        """
        pass

    def test_get_run(self) -> None:
        """Test case for get_run

        Get a previously created Run
        """
        pass

    def test_get_run_output(self) -> None:
        """Test case for get_run_output

        Retrieve last output of a run if available
        """
        pass

    def test_get_run_stream(self) -> None:
        """Test case for get_run_stream

        Stream the run output
        """
        pass

    def test_resume_run(self) -> None:
        """Test case for resume_run

        Resume an interrupted Run
        """
        pass

    def test_search_runs(self) -> None:
        """Test case for search_runs

        Search Runs
        """
        pass


if __name__ == '__main__':
    unittest.main()
