# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.run_create import RunCreate

class TestRunCreate(unittest.TestCase):
    """RunCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunCreate:
        """Test RunCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunCreate`
        """
        model = RunCreate()
        if include_optional:
            return RunCreate(
                agent_id = '',
                thread_id = '',
                input = acp_client_v0_1.models.input_schema.Input Schema(),
                metadata = acp_client_v0_1.models.metadata.Metadata(),
                config = acp_client_v0_1.models.config.Config(),
                webhook = '',
                streaming = 'result'
            )
        else:
            return RunCreate(
                agent_id = '',
        )
        """

    def testRunCreate(self):
        """Test RunCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
