# coding: utf-8

"""
    Agent Connect Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from acp_client_v0_1.models.agent import Agent

class TestAgent(unittest.TestCase):
    """Agent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Agent:
        """Test Agent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Agent`
        """
        model = Agent()
        if include_optional:
            return Agent(
                agent_id = '',
                metadata = acp_client_v0_1.models.agent_metadata.Agent Metadata(
                    ref = acp_client_v0_1.models.agent_manifest_reference.Agent Manifest Reference(
                        name = '', 
                        version = '', 
                        url = '', ), 
                    description = '', )
            )
        else:
            return Agent(
                agent_id = '',
                metadata = acp_client_v0_1.models.agent_metadata.Agent Metadata(
                    ref = acp_client_v0_1.models.agent_manifest_reference.Agent Manifest Reference(
                        name = '', 
                        version = '', 
                        url = '', ), 
                    description = '', ),
        )
        """

    def testAgent(self):
        """Test Agent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
