---
name: Check ACP SDK

on:
  pull_request:
    branches:
      - main


# When pushing twice in a row on the same branch, the second push will be cancelled
# This prevents from having multiple builds running at the same time, for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.12.7"
  UV_VERSION: "0.7.1"

permissions:
  contents: read

# Note: consider the job names to be global if you want to require
# them to succeed for a PR. :)
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python ${{ env.PYTHON_VERSION }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          update-environment: true

      - name: Install uv
        run: |
          pipx install uv==${{ env.UV_VERSION }}

      - name: Lint check
        run: make lint_check

      - name: Format check
        run: make format_check

  sdk-code-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up python ${{ env.PYTHON_VERSION }}
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        update-environment: true

    - name: Install uv
      run: |
        pipx install uv==${{ env.UV_VERSION }}

    - name: Check code
      run: make test_gha
      shell: bash

    - name: Print summary
      run: |
        echo "## Code Check" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- uv Version: ${{ env.UV_VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "- Python Version: ${{ env.PYTHON_VERSION}}" >> $GITHUB_STEP_SUMMARY
